search:
    resource: "@SearchBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

prueba:
  path: /prueba
  defaults: { _controller: AppBundle:Default:prueba }